import { format, parseISO } from "date-fns";
import { BPReading, Goal, WeeklyStats } from "../types";
import { classifyBP } from "../constants/bpRanges";

export type DoctorReport = {
  patientName: string;
  goal: Goal;
  generatedAt: string;
  totalReadings: number;
  complianceRate: number;
  avgSystolic: number;
  avgDiastolic: number;
  avgBpm: number | null;
  highestReading: BPReading | null;
  lowestReading: BPReading | null;
  weeklyStats: WeeklyStats[];
  summary: string;
};

export function generateReportData(
  patientName: string,
  goal: Goal,
  readings: BPReading[],
): DoctorReport {
  if (readings.length === 0) {
    return {
      patientName,
      goal,
      generatedAt: new Date().toISOString(),
      totalReadings: 0,
      complianceRate: 0,
      avgSystolic: 0,
      avgDiastolic: 0,
      avgBpm: null,
      highestReading: null,
      lowestReading: null,
      weeklyStats: [],
      summary: "No readings recorded during this period.",
    };
  }

  // averages
  const avgSystolic = Math.round(
    readings.reduce((sum, r) => sum + r.systolic, 0) /
      readings.length,
  );
  const avgDiastolic = Math.round(
    readings.reduce((sum, r) => sum + r.diastolic, 0) /
      readings.length,
  );

  const bpmReadings = readings.filter((r) => r.bpm !== null);
  const avgBpm =
    bpmReadings.length > 0
      ? Math.round(
          bpmReadings.reduce((sum, r) => sum + (r.bpm ?? 0), 0) /
            bpmReadings.length,
        )
      : null;

  // highest and lowest
  const highestReading = readings.reduce((prev, curr) =>
    curr.systolic > prev.systolic ? curr : prev,
  );
  const lowestReading = readings.reduce((prev, curr) =>
    curr.systolic < prev.systolic ? curr : prev,
  );

  // compliance rate
  const uniqueDays = new Set(
    readings.map((r) => r.loggedAt.split("T")[0]),
  ).size;
  const complianceRate = Math.round(
    (uniqueDays / goal.durationDays) * 100,
  );

  // weekly stats
  const weeklyGroups: Record<string, BPReading[]> = {};
  readings.forEach((reading) => {
    const weekKey = `Week ${getWeekNumber(parseISO(reading.loggedAt))}`;
    if (!weeklyGroups[weekKey]) weeklyGroups[weekKey] = [];
    weeklyGroups[weekKey].push(reading);
  });

  const weeklyStats: WeeklyStats[] = Object.entries(weeklyGroups).map(
    ([, weekReadings]) => ({
      avgSystolic: Math.round(
        weekReadings.reduce((s, r) => s + r.systolic, 0) /
          weekReadings.length,
      ),
      avgDiastolic: Math.round(
        weekReadings.reduce((s, r) => s + r.diastolic, 0) /
          weekReadings.length,
      ),
      totalReadings: weekReadings.length,
      complianceRate: Math.round(
        (new Set(weekReadings.map((r) => r.loggedAt.split("T")[0]))
          .size /
          7) *
          100,
      ),
      bestDay: weekReadings.reduce((best, curr) =>
        curr.systolic < (best?.systolic ?? Infinity) ? curr : best,
      ).loggedAt,
    }),
  );

  // plain language summary
  const classification = classifyBP(avgSystolic, avgDiastolic);
  const startFormatted = format(
    parseISO(goal.startDate),
    "MMMM d, yyyy",
  );
  const endFormatted = format(parseISO(goal.endDate), "MMMM d, yyyy");

  const summary =
    `${patientName} completed a ${goal.durationDays}-day blood pressure ` +
    `tracking program from ${startFormatted} to ${endFormatted}. ` +
    `A total of ${readings.length} readings were recorded across ` +
    `${uniqueDays} days (${complianceRate}% compliance). ` +
    `The average blood pressure over this period was ${avgSystolic}/${avgDiastolic} mmHg, ` +
    `which falls in the ${classification.label} range. ` +
    `${avgBpm !== null ? `Average heart rate was ${avgBpm} bpm. ` : ""}` +
    `This report was generated by Steadii on ${format(new Date(), "MMMM d, yyyy")}.`;

  return {
    patientName,
    goal,
    generatedAt: new Date().toISOString(),
    totalReadings: readings.length,
    complianceRate,
    avgSystolic,
    avgDiastolic,
    avgBpm,
    highestReading,
    lowestReading,
    weeklyStats,
    summary,
  };
}

function getWeekNumber(date: Date): number {
  const start = new Date(date.getFullYear(), 0, 1);
  const diff = Math.floor(
    (date.getTime() - start.getTime()) / 86400000,
  );
  return Math.ceil((diff + start.getDay() + 1) / 7);
}
